import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {gunzipSync} from 'node:zlib';
import {ERAS,REPOSITORY,eraFor,escapeHTML as esc,normalize,dailySelection,contributionURL} from '../src/lib/history.mjs';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const TARGET=path.join(ROOT,'_site');
const readJSON=async name=>JSON.parse(await fs.readFile(path.join(ROOT,name),'utf8'));
const site=await readJSON('content/site.json');
const curated=await readJSON('content/curated.json');
const photos=await readJSON('content/photographs.json');
const overrides=await readJSON('content/overrides.json');
const imported=JSON.parse(gunzipSync(await fs.readFile(path.join(ROOT,'content/martyrs-mirror.json.gz'))));
const base=(process.env.SITE_BASE_PATH||'').replace(/\/$/,'');
if(base && !/^\/(?:[a-zA-Z0-9._-]+\/)*[a-zA-Z0-9._-]+$/.test(base))throw new Error('Invalid SITE_BASE_PATH');
const origin=(process.env.SITE_ORIGIN||'https://truechristian.github.io').replace(/\/$/,'');
if(!/^https?:\/\/[^/?#]+$/.test(origin))throw new Error('SITE_ORIGIN must be an origin without a path');
const url=(route='')=>`${base}/${route.replace(/^\//,'')}`;
const canonical=route=>origin+url(route);
const pretty=title=>title===title.toUpperCase()?title.toLowerCase().replace(/\b[a-z]/g,c=>c.toUpperCase()):title;
function readableMarkdown(markup){
  const entities={'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&#x27;':"'",'&#39;':"'"};
  return markup.replace(/<img\b[^>]*>/g,'').replace(/<\/(?:p|div|blockquote|li|tr|h[1-6])>/g,'\n\n')
    .replace(/<br\s*\/?\s*>/g,'\n').replace(/<[^>]+>/g,'').replace(/&(?:amp|lt|gt|quot|#x27|#39);/g,e=>entities[e])
    .replace(/[ \t]+/g,' ').replace(/\n[ \t]+/g,'\n').replace(/\n{3,}/g,'\n\n').trim();
}
const records=[...imported.records.map(r=>({...r,title:pretty(r.title),originalTitle:r.title})),...curated].map(r=>{
  const entry={...r,...(overrides[r.slug]||{})};
  if(!/^[a-z0-9-]+$/.test(entry.slug))throw new Error('Unsafe record slug');
  entry.era=eraFor(entry);
  entry.route=`${{story:'stories',event:'events',person:'people',tradition:'traditions'}[entry.kind]}/${entry.slug}/`;
  entry.text=entry.text||(entry.paragraphs||[]).join('\n\n');
  entry.textLength=entry.text.length;
  return entry;
});
if(new Set(records.map(r=>r.slug)).size!==records.length)throw new Error('Duplicate record slugs');
const bySlug=new Map(records.map(r=>[r.slug,r]));
for(const slug of Object.keys(overrides))if(!bySlug.has(slug))throw new Error(`Unknown override ${slug}`);
for(const r of records)for(const id of [...(r.people||[]),...(r.traditions||[])])if(!bySlug.has(id))throw new Error(`Unknown relationship ${id}`);

const allPeople=records.filter(r=>r.kind==='person');
const personNames=new Map(allPeople.map(p=>[p.slug,[p.title,...p.aliases].map(normalize)]));
const mentions=new Map(records.map(record=>{
  const hay=normalize(record.title+' '+record.text);
  return [record.slug,allPeople.filter(p=>personNames.get(p.slug).some(name=>hay.includes(name)))];
}));
const mentionedPeople=record=>mentions.get(record.slug)||[];
for(const record of records)if(record.kind==='story')record.aliases=[...new Set(mentionedPeople(record).flatMap(p=>[p.title,...p.aliases]))];
const summary=r=>({slug:r.slug,title:r.title,kind:r.kind,route:r.route,era:r.era,date:r.date,
  status:r.status,category:r.category,summary:r.summary,aliases:r.aliases||[],textLength:r.textLength,
  image:r.images?.[0]||null});
const catalog=records.map(summary);
const footer=(await fs.readFile(path.join(ROOT,'vendor/theme/src/html/site-footer.html'),'utf8')).replaceAll('src="/assets/',`src="${base}/assets/`);

// Build in a new directory so repeated builds cannot reuse stale deployment URLs.
const OUT=await fs.mkdtemp(path.join(ROOT,'.history-build-'));
await fs.cp(path.join(ROOT,'sources'),path.join(OUT,'sources'),{recursive:true});
await fs.cp(path.join(ROOT,'vendor/theme/assets'),path.join(OUT,'assets'),{recursive:true});
await fs.cp(path.join(ROOT,'vendor/theme/dist'),path.join(OUT,'assets/theme'),{recursive:true});
await fs.cp(path.join(ROOT,'src/lib'),path.join(OUT,'assets/lib'),{recursive:true});
for(const filename of ['site.css','app.mjs','search-worker.mjs'])await fs.copyFile(path.join(ROOT,'src',filename),path.join(OUT,'assets',filename));
await fs.writeFile(path.join(OUT,'assets/catalog.json'),JSON.stringify(catalog));
await fs.writeFile(path.join(OUT,'assets/search-index.json'),JSON.stringify(records.map(r=>({...summary(r),normalized:normalize([r.title,r.originalTitle,r.summary,r.text,...(r.aliases||[])].join(' '))}))));
const routes=[];

function header(current){
  const item=(label,route,key)=>`<li${current===key?' class="is-active"':''}><a href="${url(route)}"${current===key?' aria-current="page"':''}>${label}</a></li>`;
  return `<header class="tcc-site-header tm-header" data-tcc-global-header><div class="tcc-header__container tcc-container">
    <a class="tcc-header__brand uk-logo" href="https://truechristian.church/" aria-label="A True Christian Church home"><img src="${url('assets/brand/logo.jpg')}" width="288" height="77" alt="A True Christian Church"></a>
    <button class="tcc-header__toggle" type="button" aria-controls="tcc-primary-navigation" aria-expanded="false"><span class="tcc-visually-hidden">Open menu</span><span aria-hidden="true">☰</span></button>
    <nav id="tcc-primary-navigation" class="tcc-header__navigation" aria-label="Primary navigation"><button class="tcc-header__close" type="button" aria-label="Close menu"><span aria-hidden="true">×</span></button><ul class="tcc-header__menu uk-navbar-nav">
    ${item('Home','','home')}${item('Timeline','timeline/','timeline')}${item('Stories','stories/','stories')}
    <li class="has-submenu"><button type="button" aria-expanded="false" aria-haspopup="true">Explore</button><ul>${item('People','people/','people')}${item('Traditions','traditions/','traditions')}${item('Sources','sources/','sources')}${item('About this archive','about/','about')}</ul></li>
    ${item('Search','search/','search')}${item('Contribute','contribute/','contribute')}</ul></nav><button class="tcc-header__scrim" type="button" tabindex="-1" aria-label="Close menu"></button></div></header>`;
}
function eraNav(active=''){
  return `<div class="era-band"><div class="tcc-container era-label"><span>Explore through time</span><span>Present → past</span></div><nav class="era-scroll tcc-container" aria-label="Historical eras">${ERAS.map(e=>`<a class="era-stop${active===e.id?' is-current':''}" href="${url('timeline/')}#${e.id}" data-era-link="${e.id}"><span>${e.short}</span><strong>${esc(e.title)}</strong><i aria-hidden="true"></i></a>`).join('')}</nav></div>`;
}
function card(r){
  return `<article class="story-card"><div class="card-meta"><span>${esc(r.date?.label||'Date to document')}</span><span>${esc(r.kind==='story'?r.category:r.kind)}</span></div><h3><a href="${url(r.route)}">${esc(r.title)}</a></h3><p>${esc(r.summary||'Read this section in the source collection.')}</p><span class="card-action">${r.status==='Research needed'?'Help document this history':'Read the story'} <span aria-hidden="true">→</span></span></article>`;
}
const cards=list=>`<div class="card-grid">${list.map(card).join('')}</div>`;
function pageLinks(title,route,record={}){
  return `<aside class="page-tools" aria-label="Page sources and contributions"><a href="${url(route+'README.md')}">Read this page as Markdown</a><a href="${esc(contributionURL({...record,title:record.title||title},canonical(route)))}" rel="noopener">${record.status==='Research needed'?'Add the missing history':'Suggest a correction or addition'}</a></aside>`;
}
function lead(kicker,title,description){return `<div class="page-lead"><p class="eyebrow">${esc(kicker)}</p><h1>${esc(title)}</h1><p class="lead">${esc(description)}</p></div>`;}
function sourceRefs(list=[]){return list.length?`<section class="reference-list"><h2>Sources and further reading</h2><ul>${list.map(s=>`<li><a href="${esc(/^https?:/.test(s.url)?s.url:url(s.url))}"${/^https?:/.test(s.url)?' rel="noopener"':''}>${esc(s.label)}</a></li>`).join('')}</ul></section>`:'';}

async function page(route,title,body,markdown,current='',record={}){
  const dir=path.join(OUT,route);await fs.mkdir(dir,{recursive:true});
  routes.push(route);
  const description=record.summary||site.description;
  const content=`<!doctype html><html lang="en" data-base="${esc(base)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>${esc(title)} · ${esc(site.title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical(route)}"><link rel="icon" href="${url('assets/favicons/favicon.ico')}"><script>try{var m=localStorage.getItem('history-theme')||'system';document.documentElement.dataset.theme=(m==='light'||m==='dark')?m:(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light')}catch(e){document.documentElement.dataset.theme=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'}</script><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600&amp;family=Raleway:wght@400;500;600&amp;display=swap"><link rel="stylesheet" href="${url('assets/theme/truechristian-theme.css')}"><link rel="stylesheet" href="${url('assets/site.css')}"><script defer src="${url('assets/theme/truechristian-theme.js')}"></script><script type="module" src="${url('assets/app.mjs')}"></script></head><body><a class="skip-link" href="#main">Skip to content</a>${header(current)}<div class="utility-bar tcc-container"><a class="archive-name" href="${url()}">Anabaptist Church History</a><label class="theme-control">Appearance <select id="theme-mode" aria-label="Appearance"><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label></div>${eraNav(record.era)}<main id="main" class="tcc-container" tabindex="-1">${body}${pageLinks(title,route,record)}</main>${footer}</body></html>`;
  await fs.writeFile(path.join(dir,'index.html'),content);
  await fs.writeFile(path.join(dir,'README.md'),`# ${title}\n\n${markdown}\n\n---\n\nPage: ${canonical(route)}\n\n[Contribute a correction or addition](${contributionURL({...record,title:record.title||title},canonical(route))})\n`);
}

const initialDaily=dailySelection(catalog);
await page('',site.title,`<section class="home-hero"><div><p class="eyebrow">People. Conviction. Living history.</p><h1>A history of faith,<br>remembered together.</h1><p class="lead">Discover the people and communities of the Radical Reformation—and the Christian witness they remembered. Follow the story from Acts to the living Anabaptist family.</p><div class="actions"><a class="button primary" href="${url('timeline/')}#radical-reformation">Explore the timeline <span aria-hidden="true">→</span></a><a class="text-link" href="${url('stories/')}">Open the story collection</a></div><form class="hero-search" action="${url('search/')}" role="search"><label for="home-search">Find a person, place, or event</label><div><input id="home-search" name="q" type="search" placeholder="Try Felix Manz, Zürich, or baptism"><button class="button" type="submit">Search</button></div></form></div><figure class="hero-figure"><img src="${url('sources/martyrs-mirror/images/i1437.jpg')}" width="880" height="700" alt="Dirk Willems reaches back to rescue his pursuer from the ice"><figcaption>Dirk Willems, 1569 · Illustration from <a href="${url('stories/mm-dirk-willems-a-d-1569/')}">Martyrs’ Mirror</a></figcaption></figure></section><section class="discovery-section"><div class="section-heading"><div><p class="eyebrow">A different window each day</p><h2>Today’s six stories</h2></div><a class="text-link" href="${url('stories/')}">Browse all ${imported.recordCount.toLocaleString()} source sections →</a></div><p class="section-note">Six selections from the archive, refreshed each day. <span id="daily-date"></span></p><div id="daily-stories">${cards(initialDaily)}</div></section><section class="home-paths"><a href="${url('people/')}"><span>01 / People</span><h2>Meet the witnesses</h2><p>Names, alternate spellings, and links to the accounts that mention them.</p></a><a href="${url('traditions/')}"><span>02 / Traditions</span><h2>Follow the different streams</h2><p>Swiss Brethren, Mennonites, Hutterites, Amish, and related histories.</p></a><a href="${url('contribute/')}"><span>03 / An open archive</span><h2>Help carry the story forward</h2><p>Add a source, correct a date, or share a documented local history.</p></a></section>`,`${site.description}\n\n## Explore\n\n- [Timeline](${url('timeline/')})\n- [Stories](${url('stories/')})\n- [People](${url('people/')})\n- [Traditions](${url('traditions/')})\n- [Sources](${url('sources/')})\n- [Contribute](${url('contribute/')})\n\nThe homepage selects six source stories daily using the UTC calendar date. The timeline runs from present to past.`, 'home');

const eraPanels=ERAS.map(e=>{
  const milestones=records.filter(r=>r.era===e.id && r.kind==='event').sort((a,b)=>(b.date?.start||9999)-(a.date?.start||9999));
  const sourceStories=records.filter(r=>r.era===e.id && r.kind==='story');
  const branches=records.filter(r=>r.era===e.id && r.kind==='tradition');
  return `<section id="${e.id}" class="era-panel" data-era-panel="${e.id}"><div class="section-heading"><div><p class="eyebrow">${e.short}</p><h2>${esc(e.title)}</h2></div><a class="text-link" href="${url('stories/')}?era=${e.id}">${sourceStories.length} source sections →</a></div><p class="lead">${esc(e.description)}</p><div class="timeline-track" tabindex="0" role="region" aria-label="${esc(e.title)} milestones, present to past">${milestones.map(r=>`<article class="timeline-event"><span class="timeline-dot" aria-hidden="true"></span><p class="timeline-year">${esc(r.date?.label||(r.era==='living-traditions'?'Continuing today':'Date not assigned'))}</p><h3><a href="${url(r.route)}">${esc(r.title)}</a></h3><p>${esc(r.summary)}</p></article>`).join('')||'<p>Explore the source accounts below. Detailed milestones can be contributed as research grows.</p>'}</div>${branches.length?`<h3>Traditions and histories in this era</h3><div class="topic-chips">${branches.map(r=>`<a href="${url(r.route)}">${esc(r.title)}${r.status==='Research needed'?' <small>History invited</small>':''}</a>`).join('')}</div>`:''}${sourceStories.length?cards(sourceStories.filter(r=>r.images?.length).concat(sourceStories).filter((r,i,a)=>a.findIndex(x=>x.slug===r.slug)===i).slice(0,6)):''}<p><a class="button" href="${esc(contributionURL({title:e.title,slug:e.id},canonical('timeline/')+'#'+e.id,'missing'))}">Add history to this era</a></p></section>`;
}).join('');
await page('timeline/','The timeline',lead('Present → past','Follow the story through time','Choose an era above, then follow a milestone into its people, original accounts, and sources.')+`<div class="timeline-controls"><a href="#living-traditions">Present day</a><a href="#radical-reformation">1525 and the Reformation</a><a href="#acts-and-early-church">Christian beginnings</a></div>${eraPanels}<section class="source-callout"><h2>The photographed timeline</h2><p>The Church History photographs guide coverage of the later traditions and migrations.</p><a href="${url('sources/church-history/')}"><img loading="lazy" src="${url('sources/church-history/photos/IMG_9373.jpg')}" alt="Photographed Anabaptist and Mennonite timeline, from 1500 into the twentieth century"></a><p><a href="${url('sources/church-history/')}">Explore the timeline close-ups and their sources →</a></p></section>`,ERAS.map(e=>`## ${e.title} (${e.short})\n\n${e.description}\n\n`+records.filter(r=>r.era===e.id && r.kind==='event').map(r=>`- ${r.date?.label||'Ongoing'}: [${r.title}](${url(r.route)})`).join('\n')).join('\n\n'),'timeline');

const options=(items,valueKey='id',labelKey='title')=>items.map(e=>`<option value="${esc(e[valueKey])}">${esc(e[labelKey])}</option>`).join('');
await page('stories/','Stories and source accounts',lead('The source collection','Stories, letters, and witnesses','Read the individual accounts of Martyrs’ Mirror, with their original wording and a direct route back to the complete source.')+`<form class="filter-form" id="archive-filters"><label>Search titles<input name="q" type="search" placeholder="Name, place, or title"></label><label>Era<select name="era"><option value="">Every era</option>${options(ERAS)}<option value="source-context">Source introductions and context</option></select></label><label>Section type<select name="category"><option value="">All sections</option>${[...new Set(imported.records.map(r=>r.category))].map(c=>`<option>${esc(c)}</option>`).join('')}</select></label><button class="button" type="submit">Filter</button></form><p id="archive-count" class="result-count" aria-live="polite">${imported.recordCount} source sections</p><div id="archive-results">${cards(records.filter(r=>r.kind==='story').slice(0,36))}</div><button id="archive-more" class="button more-button" type="button" hidden>Show more stories</button><noscript><p>Enable JavaScript to filter the collection. The complete edition remains available below.</p></noscript><p><a href="${url('sources/martyrs-mirror/')}">Open the complete edition and chapter guide →</a></p>`,`${imported.recordCount} original source sections.\n\n`+records.filter(r=>r.kind==='story').map(r=>`- [${r.title}](${url(r.route)}) · ${r.date?.label||'Source context'}`).join('\n'),'stories');

for(const [kind,title,intro] of [['person','People','Explore key individuals and the source accounts that mention them. Search also finds names throughout the complete text, including people who do not yet have a profile.'],['tradition','Traditions and related histories','Explore different Anabaptist streams. Names on the photographed timeline have a place here, including histories that contributors can help document.']]){
  const selection=records.filter(r=>r.kind===kind);
  await page(`${kind==='person'?'people':'traditions'}/`,title,lead('The wider story',title,intro)+cards(selection),intro+'\n\n'+selection.map(r=>`- [${r.title}](${url(r.route)})${r.status==='Research needed'?' — History invited':''}`).join('\n'),kind==='person'?'people':'traditions');
}

for(const r of records){
  const people=[...new Set([...(r.people||[]),...mentionedPeople(r).filter(p=>p.slug!==r.slug).map(p=>p.slug)])].map(id=>bySlug.get(id));
  const traditions=(r.traditions||[]).map(id=>bySlug.get(id));
  const related=r.kind==='person'?records.filter(x=>x.slug!==r.slug && (x.people?.includes(r.slug) || (x.kind==='story' && mentionedPeople(x).some(p=>p.slug===r.slug)))):records.filter(x=>x.slug!==r.slug && (x.traditions?.includes(r.slug) || (r.kind==='story' && x.kind==='story' && x.chapter===r.chapter)));
  const sourceNotice=r.source==='martyrs-mirror'?`<div class="source-notice"><strong>From Martyrs’ Mirror</strong><p>Original historical wording. ${esc(r.date?.basis||'This section has no event date assigned.')} Earlier accounts express the book’s perspective on Christian continuity.</p>${r.slug==='mm-felix-mantz-a-d-1526'?`<p>The heading gives 1526; later references date Manz’s execution to 1527. <a href="${url('events/felix-manz-execution/')}">Compare the dates and sources.</a></p>`:''}</div>`:'';
  const gap=r.status==='Research needed'?`<div class="research-notice"><strong>Help document this history</strong><p>${esc(r.date?.basis||'Dates, people, and a detailed account are still being gathered.')} Share what you can add, with sources, for review.</p><a class="button" href="${esc(contributionURL(r,canonical(r.route),'missing'))}">Contribute this history →</a></div>`:'';
  const article=r.html?r.html.replaceAll('__BASE__',base):(r.paragraphs||[]).map(p=>`<p>${esc(p)}</p>`).join('');
  const original=r.source==='martyrs-mirror'?`<details class="source-details"><summary>Original heading and source location</summary><p>${esc(r.originalTitle)}</p><p>${esc(r.part)} · ${esc(r.chapter)}</p><a href="${url('sources/martyrs-mirror/original.html')}#${esc(r.sourceAnchor||'')}" rel="noopener">Read this location in the complete edition</a>${r.sourcePages?.length?`<p>Original page markers: ${esc(r.sourcePages.join(', '))}</p>`:''}</details>`:'';
  const relationships=(list,label)=>list.length?`<section class="related-topics"><h2>${label}</h2><div class="topic-chips">${list.map(x=>`<a href="${url(x.route)}">${esc(x.title)}</a>`).join('')}</div></section>`:'';
  await page(r.route,r.title,`<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="${url()}">Home</a><span aria-hidden="true">/</span><a href="${url(r.route.split('/')[0]+'/')}">${esc(r.kind==='story'?'Stories':r.kind==='person'?'People':r.kind==='event'?'Events':'Traditions')}</a></nav><article class="reading-page"><div class="reading-heading"><p class="eyebrow">${esc(r.date?.label||'Date to document')} · ${esc(r.kind==='story'?r.category:r.kind)}</p><h1>${esc(r.title)}</h1>${r.kind!=='story'?`<p class="lead">${esc(r.summary)}</p>`:''}${r.aliases?.length?`<p class="aliases">Also searchable as: ${esc(r.aliases.join(' · '))}</p>`:''}</div>${sourceNotice}${gap}<div class="prose">${article}</div>${original}${sourceRefs(r.references)}${relationships(people,'People in this history')}${relationships(traditions,'Related traditions')}${related.length?`<section class="related-stories"><h2>${r.kind==='person'?'Accounts and events mentioning this person':'Continue exploring'}</h2>${cards(related.slice(0,6))}${r.kind==='person'?`<p><a href="${url('search/')}?q=${encodeURIComponent(r.title)}">Search the full archive for this name →</a></p>`:''}</section>`:''}</article>`,`${r.date?.label||'Date not assigned'} · ${r.status}\n\n${r.source==='martyrs-mirror'?`Source: Martyrs’ Mirror. Original heading: ${r.originalTitle}\n\n${r.date?.basis||''}\n\n`:''}${r.html?readableMarkdown(r.html):r.text}\n\n${r.images?.map(i=>`![Illustration from Martyrs’ Mirror](${url(i)})`).join('\n\n')||''}\n\n${r.references?.map(s=>`- [${s.label}](${/^https?:/.test(s.url)?s.url:url(s.url)})`).join('\n')||''}`,r.kind==='story'?'stories':r.kind==='person'?'people':r.kind==='tradition'?'traditions':'timeline',r);
}

await page('events/','Events and milestones',lead('Milestones','Events and milestones','Follow the events that connect the people, source accounts, and traditions.')+cards(records.filter(r=>r.kind==='event')),records.filter(r=>r.kind==='event').map(r=>`- [${r.title}](${url(r.route)})`).join('\n'),'timeline');
await page('search/','Search the archive',lead('The whole collection','Search the archive','Find names, places, phrases, and events throughout the complete source text and the growing historical overviews.')+`<form id="search-form" class="filter-form" role="search"><label class="query-field">Search<input id="search-query" name="q" type="search" placeholder="Try Anneken Jans, prison, or Zürich" autocomplete="off"></label><label>Record type<select name="kind"><option value="">Every type</option><option value="story">Stories and letters</option><option value="person">People</option><option value="event">Events</option><option value="tradition">Traditions</option></select></label><label>Era<select name="era"><option value="">Every era</option>${options(ERAS)}<option value="source-context">Source context</option></select></label><div class="year-fields"><label>From year<input name="from" type="number" min="1" max="9999" placeholder="1500"></label><label>To year<input name="to" type="number" min="1" max="9999" placeholder="2026"></label></div><button class="button primary" type="submit">Search</button></form><p class="section-note">Alternate spellings on people’s profiles are searchable. Dates assigned only to a century are treated as ranges.</p><p id="search-status" class="result-count" role="status">Enter a word, phrase, or name to begin.</p><div id="search-results"></div><button id="search-more" class="button more-button" hidden type="button">Show more results</button><noscript><p>Full-text search requires JavaScript. You can browse the timeline, people, and complete source edition without it.</p></noscript>`,`Search covers ${records.length} records and all imported text.\n\nFilter by record type, era, and date range. Source dates remain attributed to their headings or containing century. Search does not require an account.`,'search');

await page('sources/','Sources and acknowledgements',lead('Evidence and memory','Sources and acknowledgements','Read the original material, inspect the timeline photographs, and see how the archive handles dates, attribution, and historical perspectives.')+`<div class="source-grid">${site.sources.map(s=>`<article class="source-card"><p class="eyebrow">${esc(s.author)}</p><h2>${esc(s.title)}</h2><p>${esc(s.description)}</p><a class="button" href="${url('sources/'+s.id+'/')}">Explore this source →</a></article>`).join('')}</div><div class="source-notice"><h2>How to read this archive</h2><p>Original accounts, editorial overviews, and histories awaiting documentation are identified separately on their pages. A date in a historical source is not automatically an independently verified date. Early Christian and medieval accounts are part of the memory recorded in Martyrs’ Mirror; their presence does not establish a continuous institutional genealogy.</p></div>`,site.sources.map(s=>`## ${s.title}\n\n${s.author}\n\n${s.description}\n\n${s.url}`).join('\n\n'),'sources');
const chapterRecords=records.filter(r=>r.source==='martyrs-mirror' && r.headingLevel<4);
await page('sources/martyrs-mirror/','The Martyrs’ Mirror collection',lead('The foundation collection','Martyrs’ Mirror',`${imported.recordCount} source sections, ${imported.imageCount} supplied illustrations, and the complete original edition.`)+`<div class="actions"><a class="button primary" href="${url('stories/')}">Browse the individual accounts</a><a class="button" href="${url('sources/martyrs-mirror/original.html')}">Read the intact edition</a></div><div class="prose"><p>The supplied English text is preserved without rewriting the historical accounts. Its source heading, containing century, page markers, and original anchor accompany each imported section. Footnotes and cross-references lead back to the complete edition.</p><p>Public-domain book text and illustrations are distinct from the Behalt painting. The original Gutenberg notices are retained with the source document.</p></div><h2>Chapter and context guide</h2><ul class="chapter-list">${chapterRecords.map(r=>`<li><a href="${url(r.route)}">${esc(r.title)}</a></li>`).join('')}</ul>`,`${imported.recordCount} sections and ${imported.imageCount} images imported from the supplied ZIP.\n\nSource SHA-256: ${imported.sourceSha256}\n\n[Complete original edition](${url('sources/martyrs-mirror/original.html')})\n\n`+chapterRecords.map(r=>`- [${r.title}](${url(r.route)})`).join('\n'),'sources');

const photoFigures=photos.map(p=>`<figure class="photo-card"><a href="${url('sources/church-history/photos/'+p.file)}"><img loading="lazy" src="${url('sources/church-history/photos/'+p.file)}" alt="${esc(p.title)}; ${esc(p.file)}"></a><figcaption><strong>${esc(p.title)}</strong><span>${p.file} · ${esc(p.category)}</span>${p.mural?`<span>Behalt artwork: <a href="https://behalt.com/meet-heinz-gaugel/">Heinz Gaugel</a> · <a href="https://behalt.com/">Amish & Mennonite Heritage Center</a>.</span>`:'<span>Timeline or exhibit photographed at the Amish & Mennonite Heritage Center.</span>'}<span>Photograph supplied by the site owner.</span></figcaption></figure>`).join('');
await page('sources/church-history/','The photographed church history timeline',lead('Forty supplied photographs','The photographed timeline','Inspect the original timeline overviews, branch names, and close-ups that guide this archive’s coverage beyond Martyrs’ Mirror.')+`<p class="section-note">Select a photograph to open it at full display size. Timeline material is identified as public domain by the contributor; mural imagery is separately acknowledged below.</p><div class="photo-grid">${photoFigures}</div>`,photos.map(p=>`- [${p.title}: ${p.file}](${url('sources/church-history/photos/'+p.file)})${p.mural?' · Behalt by Heinz Gaugel, Amish & Mennonite Heritage Center':''}`).join('\n'),'sources');
await page('sources/behalt/','Behalt: acknowledgements',lead('Art and historical memory','Behalt','Acknowledge the project and artist behind the supplied video and exhibit-panel imagery.')+`<figure class="behalt-reference"><img loading="lazy" src="${url('sources/behalt/reference.jpg')}" width="910" height="512" alt="A section of the Behalt history mural photographed from the supplied video"><figcaption>Behalt by <a href="https://behalt.com/meet-heinz-gaugel/">Heinz Gaugel</a>, at the <a href="https://behalt.com/">Amish & Mennonite Heritage Center</a>, Holmes County, Ohio. Frame from the site owner’s supplied video.</figcaption></figure><div class="prose"><p>Behalt is a circular mural that interprets the history of the Amish, Mennonites, and Hutterites. Heinz Gaugel completed the painting in 1992. It remains an artistic and historical interpretation, while the photographed timelines provide the principal guide for extending this site.</p><p>Every use of mural imagery in this archive acknowledges Heinz Gaugel and links to the Amish & Mennonite Heritage Center. The painting’s status is kept separate from the public-domain Martyrs’ Mirror material and the contributor’s timeline material.</p></div>${sourceRefs([{label:'Behalt project',url:'https://behalt.com/behalt-cyclorama/'},{label:'Heinz Gaugel: the artist',url:'https://behalt.com/meet-heinz-gaugel/'}])}`,'Behalt by Heinz Gaugel.\n\nAmish & Mennonite Heritage Center, Holmes County, Ohio.\n\nhttps://behalt.com/behalt-cyclorama/\n\nhttps://behalt.com/meet-heinz-gaugel/\n\nThe supplied video was inspected as a visual reference. A credited still is used on this acknowledgement page. The site’s main navigation and historical coverage are based on source accounts and the timeline photographs.','sources');

const gaps=records.filter(r=>r.status==='Research needed');
await page('contribute/','Contribute to the history',lead('An archive we build together','Contribute to the history','Share a source, correct an account, or help document a community that is missing from the story.')+`<div class="contribute-steps"><article><span>01</span><h2>Choose a page or topic</h2><p>Use the contribution link on any page. It carries that page’s title, address, and record into the issue.</p></article><article><span>02</span><h2>Add what you know</h2><p>Include dates, people, places, and sources. For photographs, include the creator and permission or public-domain basis.</p></article><article><span>03</span><h2>Submit for review</h2><p>A maintainer reviews the evidence and updates the archive. A GitHub account is needed to submit an issue.</p></article></div><p><a class="button primary" href="${esc(contributionURL({title:'New Anabaptist history contribution'},canonical('contribute/'),'missing'))}">Open a history contribution →</a> <a class="text-link" href="${REPOSITORY}/issues">View existing contributions</a></p><h2>Histories you can help document</h2>${cards(gaps)}`,`Contributions use GitHub issues and are reviewed before publication.\n\n1. Choose a page.\n2. Add sources, dates, people, places, and image credits.\n3. Submit for review.\n\n## Histories invited\n\n`+gaps.map(r=>`- [${r.title}](${url(r.route)})`).join('\n'),'contribute');
await page('about/','About this archive',lead('Purpose and approach','A shared record of Anabaptist history','An open archive of the Radical Reformation and the many communities whose histories grew from it.')+`<div class="prose"><p>This project makes church history easier to explore through time, people, events, and source accounts. It includes the wider Anabaptist family rather than treating one tradition as the whole story.</p><p>The supporting fellowship identifies its own background with Charity Ministries and the Agape stream. Those modern histories are marked as owner-supplied accounts inviting documentation.</p><p>Martyrs’ Mirror provides the extensive foundation collection. The Church History photographs guide coverage of later migrations and traditions. Editorial overviews connect records while retaining visible references and uncertainty.</p><p>The site is published as static pages on GitHub Pages. Search and daily selections run in the visitor’s browser. Appearance follows the system by default, with an optional setting saved on the device.</p></div>`,`${site.description}\n\nThe archive includes the wider Anabaptist family. Original historical accounts and current editorial overviews retain their sources. Incomplete modern histories invite documented contributions.\n\nThe theme is taken from trueChristian/theme at ${site.themeCommit}.`,'about');
await page('not-found/','Page not found',lead('Find your way back','This page could not be found','The archive may have changed. Search for the person or event, or return to the timeline.')+`<div class="actions"><a class="button primary" href="${url('search/')}">Search the archive</a><a class="button" href="${url('timeline/')}">Open the timeline</a></div>`,'The requested page could not be found. Use the search or timeline.');
await fs.copyFile(path.join(OUT,'not-found/index.html'),path.join(OUT,'404.html'));
await fs.writeFile(path.join(OUT,'.nojekyll'),'');
await fs.writeFile(path.join(OUT,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${canonical('sitemap.xml')}\n`);
await fs.writeFile(path.join(OUT,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(r=>`<url><loc>${esc(canonical(r))}</loc></url>`).join('')}</urlset>`);
await fs.writeFile(path.join(OUT,'build-info.json'),JSON.stringify({records:records.length,sourceSections:imported.recordCount,sourceImages:imported.imageCount,photographs:photos.length,pages:routes.length,base,themeCommit:site.themeCommit}));
await fs.rm(TARGET,{recursive:true,force:true,maxRetries:3,retryDelay:100});
await fs.rename(OUT,TARGET);
console.log(`Built ${routes.length} pages: ${imported.recordCount} source sections, ${curated.length} curated records, ${photos.length} photographs.`);
